In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import xarray as xr

from tinypet.data import XarraySource, Seq
import tinypet.operations as ops
import tinypet.sampler as sp

In [3]:
era5 = xr.open_zarr('gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr')

In [4]:
era5

<xarray.Dataset> Size: 175GB
Dimensions:                                           (time: 93544,
                                                       longitude: 64,
                                                       latitude: 32, level: 13)
Coordinates:
  * latitude                                          (latitude) float64 256B ...
  * level                                             (level) int64 104B 50 ....
  * longitude                                         (longitude) float64 512B ...
  * time                                              (time) datetime64[ns] 748kB ...
Data variables: (12/62)
    10m_u_component_of_wind                           (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    10m_v_component_of_wind                           (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    10m_wind_speed                                    (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    2m_dewpoint_temperature                           (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    2m_temperature                                    (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    above_ground                                      (time, level, longitude, latitude) float32 10GB dask.array<chunksize=(100, 13, 64, 32), meta=np.ndarray>
    ...                                                ...
    volumetric_soil_water_layer_1                     (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_2                     (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_3                     (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_4                     (time, longitude, latitude) float32 766MB dask.array<chunksize=(100, 64, 32), meta=np.ndarray>
    vorticity                                         (time, level, longitude, latitude) float32 10GB dask.array<chunksize=(100, 13, 64, 32), meta=np.ndarray>
    wind_speed                                        (time, level, longitude, latitude) float32 10GB dask.array<chunksize=(100, 13, 64, 32), meta=np.ndarray>

In [5]:
source = XarraySource(era5, dim="time")

In [6]:
len(source)

93544

In [7]:
source.index

<xarray.DataArray 'time' (time: 93544)> Size: 748kB
array(['1959-01-01T00:00:00.000000000', '1959-01-01T06:00:00.000000000',
       '1959-01-01T12:00:00.000000000', ..., '2023-01-10T06:00:00.000000000',
       '2023-01-10T12:00:00.000000000', '2023-01-10T18:00:00.000000000'],
      shape=(93544,), dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 748kB 1959-01-01 ... 2023-01-10T18:00:00

In [8]:
next(iter(source))

<xarray.Dataset> Size: 2MB
Dimensions:                                           (longitude: 64,
                                                       latitude: 32, level: 13)
Coordinates:
  * latitude                                          (latitude) float64 256B ...
  * level                                             (level) int64 104B 50 ....
  * longitude                                         (longitude) float64 512B ...
    time                                              datetime64[ns] 8B 1959-...
Data variables: (12/62)
    10m_u_component_of_wind                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    10m_v_component_of_wind                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    10m_wind_speed                                    (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    2m_dewpoint_temperature                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    2m_temperature                                    (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    above_ground                                      (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>
    ...                                                ...
    volumetric_soil_water_layer_1                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_2                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_3                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_4                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    vorticity                                         (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>
    wind_speed                                        (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>

In [9]:
source["2021-01-01T06"]

<xarray.Dataset> Size: 2MB
Dimensions:                                           (longitude: 64,
                                                       latitude: 32, level: 13)
Coordinates:
  * latitude                                          (latitude) float64 256B ...
  * level                                             (level) int64 104B 50 ....
  * longitude                                         (longitude) float64 512B ...
    time                                              datetime64[ns] 8B 2021-...
Data variables: (12/62)
    10m_u_component_of_wind                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    10m_v_component_of_wind                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    10m_wind_speed                                    (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    2m_dewpoint_temperature                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    2m_temperature                                    (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    above_ground                                      (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>
    ...                                                ...
    volumetric_soil_water_layer_1                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_2                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_3                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_4                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    vorticity                                         (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>
    wind_speed                                        (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>

In [10]:
select = ops.Select(["2m_temperature", "geopotential"])
level = ops.Sel(level=[50, 100, 150, 200])
compute = ops.Compute(scheduler='single-threaded')
mean = ops.Mean(dim="level")
rename = ops.Rename({"latitude": "lat", "longitude": "lon"})
stack = ops.ToStackedArray("feats", sample_dims=["lat", "lon"])

In [11]:
pipeline = stack(rename(mean(compute(level(select(source))))))
pipeline["2021-01-01T06"]

<xarray.DataArray '2m_temperature' (lon: 64, lat: 32, feats: 2)> Size: 16kB
array([[[   241.77635, 145332.05   ],
        [   244.7752 , 145182.16   ],
        [   244.02347, 145215.55   ],
        ...,
        [   273.40164, 145795.55   ],
        [   262.4984 , 145227.3    ],
        [   261.20053, 144711.78   ]],

       [[   241.47781, 145354.16   ],
        [   243.781  , 145261.14   ],
        [   241.20265, 145318.23   ],
        ...,
        [   275.8759 , 145549.56   ],
        [   269.27942, 145159.9    ],
        [   262.38083, 144712.6    ]],

       [[   241.34395, 145382.08   ],
        [   242.78674, 145365.44   ],
        [   239.28514, 145467.73   ],
        ...,
...
        ...,
        [   255.16232, 146335.14   ],
        [   250.35335, 145309.44   ],
        [   257.62784, 144716.66   ]],

       [[   243.09425, 145303.23   ],
        [   249.46544, 145099.98   ],
        [   252.24045, 145120.12   ],
        ...,
        [   257.68732, 146240.44   ],
        [   252.6207 , 145318.75   ],
        [   258.82977, 144714.58   ]],

       [[   242.35269, 145314.83   ],
        [   246.5477 , 145129.19   ],
        [   247.01332, 145148.4    ],
        ...,
        [   267.78372, 146039.45   ],
        [   256.14276, 145284.94   ],
        [   260.02017, 144712.61   ]]], shape=(64, 32, 2), dtype=float32)
Coordinates:
  * lat       (lat) float64 256B -87.19 -81.56 -75.94 ... 75.94 81.56 87.19
  * lon       (lon) float64 512B 0.0 5.625 11.25 16.88 ... 343.1 348.8 354.4
    time      datetime64[ns] 8B 2021-01-01T06:00:00
  * feats     (feats) object 16B MultiIndex
  * variable  (feats) <U14 112B '2m_temperature' 'geopotential'

In [12]:
pipeline = source | select | level | compute | mean | rename | stack
pipeline["2021-01-01T06"]

<xarray.DataArray '2m_temperature' (lon: 64, lat: 32, feats: 2)> Size: 16kB
array([[[   241.77635, 145332.05   ],
        [   244.7752 , 145182.16   ],
        [   244.02347, 145215.55   ],
        ...,
        [   273.40164, 145795.55   ],
        [   262.4984 , 145227.3    ],
        [   261.20053, 144711.78   ]],

       [[   241.47781, 145354.16   ],
        [   243.781  , 145261.14   ],
        [   241.20265, 145318.23   ],
        ...,
        [   275.8759 , 145549.56   ],
        [   269.27942, 145159.9    ],
        [   262.38083, 144712.6    ]],

       [[   241.34395, 145382.08   ],
        [   242.78674, 145365.44   ],
        [   239.28514, 145467.73   ],
        ...,
...
        ...,
        [   255.16232, 146335.14   ],
        [   250.35335, 145309.44   ],
        [   257.62784, 144716.66   ]],

       [[   243.09425, 145303.23   ],
        [   249.46544, 145099.98   ],
        [   252.24045, 145120.12   ],
        ...,
        [   257.68732, 146240.44   ],
        [   252.6207 , 145318.75   ],
        [   258.82977, 144714.58   ]],

       [[   242.35269, 145314.83   ],
        [   246.5477 , 145129.19   ],
        [   247.01332, 145148.4    ],
        ...,
        [   267.78372, 146039.45   ],
        [   256.14276, 145284.94   ],
        [   260.02017, 144712.61   ]]], shape=(64, 32, 2), dtype=float32)
Coordinates:
  * lat       (lat) float64 256B -87.19 -81.56 -75.94 ... 75.94 81.56 87.19
  * lon       (lon) float64 512B 0.0 5.625 11.25 16.88 ... 343.1 348.8 354.4
    time      datetime64[ns] 8B 2021-01-01T06:00:00
  * feats     (feats) object 16B MultiIndex
  * variable  (feats) <U14 112B '2m_temperature' 'geopotential'

In [13]:
train_dates = sp.DateRange(end="20191231")
shuffle = sp.Shuffle(seed=1234)

train_pipeline = pipeline | train_dates | shuffle
train_pipeline.index

array(['1970-07-01T12:00:00.000000000', '1979-11-15T00:00:00.000000000',
       '1997-11-24T00:00:00.000000000', ...,
       '1981-10-09T18:00:00.000000000', '2003-09-03T18:00:00.000000000',
       '1991-11-23T12:00:00.000000000'],
      shape=(89117,), dtype='datetime64[ns]')

In [14]:
max(train_pipeline.index)

np.datetime64('2019-12-31T00:00:00.000000000')

In [15]:
train_pipeline.index

array(['1982-07-24T00:00:00.000000000', '1985-08-24T06:00:00.000000000',
       '1960-01-17T06:00:00.000000000', ...,
       '1974-06-22T12:00:00.000000000', '2016-09-27T00:00:00.000000000',
       '2019-07-15T12:00:00.000000000'],
      shape=(89117,), dtype='datetime64[ns]')

In [16]:
virtual_pipeline = select | level | compute | mean | rename | stack
virtual_pipeline

In [17]:
new_pipeline = source | virtual_pipeline
new_pipeline["2021-01-01T06"]

<xarray.DataArray '2m_temperature' (lon: 64, lat: 32, feats: 2)> Size: 16kB
array([[[   241.77635, 145332.05   ],
        [   244.7752 , 145182.16   ],
        [   244.02347, 145215.55   ],
        ...,
        [   273.40164, 145795.55   ],
        [   262.4984 , 145227.3    ],
        [   261.20053, 144711.78   ]],

       [[   241.47781, 145354.16   ],
        [   243.781  , 145261.14   ],
        [   241.20265, 145318.23   ],
        ...,
        [   275.8759 , 145549.56   ],
        [   269.27942, 145159.9    ],
        [   262.38083, 144712.6    ]],

       [[   241.34395, 145382.08   ],
        [   242.78674, 145365.44   ],
        [   239.28514, 145467.73   ],
        ...,
...
        ...,
        [   255.16232, 146335.14   ],
        [   250.35335, 145309.44   ],
        [   257.62784, 144716.66   ]],

       [[   243.09425, 145303.23   ],
        [   249.46544, 145099.98   ],
        [   252.24045, 145120.12   ],
        ...,
        [   257.68732, 146240.44   ],
        [   252.6207 , 145318.75   ],
        [   258.82977, 144714.58   ]],

       [[   242.35269, 145314.83   ],
        [   246.5477 , 145129.19   ],
        [   247.01332, 145148.4    ],
        ...,
        [   267.78372, 146039.45   ],
        [   256.14276, 145284.94   ],
        [   260.02017, 144712.61   ]]], shape=(64, 32, 2), dtype=float32)
Coordinates:
  * lat       (lat) float64 256B -87.19 -81.56 -75.94 ... 75.94 81.56 87.19
  * lon       (lon) float64 512B 0.0 5.625 11.25 16.88 ... 343.1 348.8 354.4
    time      datetime64[ns] 8B 2021-01-01T06:00:00
  * feats     (feats) object 16B MultiIndex
  * variable  (feats) <U14 112B '2m_temperature' 'geopotential'

In [18]:
undo_stack = pipeline.undo()
(pipeline | undo_stack)["2021-01-01T06"]

<xarray.Dataset> Size: 17kB
Dimensions:         (lat: 32, lon: 64)
Coordinates:
  * lat             (lat) float64 256B -87.19 -81.56 -75.94 ... 81.56 87.19
  * lon             (lon) float64 512B 0.0 5.625 11.25 ... 343.1 348.8 354.4
    time            datetime64[ns] 8B 2021-01-01T06:00:00
Data variables:
    2m_temperature  (lon, lat) float32 8kB 241.8 244.8 244.0 ... 256.1 260.0
    geopotential    (lon, lat) float32 8kB 1.453e+05 1.452e+05 ... 1.447e+05

In [19]:
undo_stack_and_rename = pipeline.undo(2)
(pipeline | undo_stack_and_rename)["2021-01-01T06"]

<xarray.Dataset> Size: 17kB
Dimensions:         (latitude: 32, longitude: 64)
Coordinates:
  * latitude        (latitude) float64 256B -87.19 -81.56 -75.94 ... 81.56 87.19
  * longitude       (longitude) float64 512B 0.0 5.625 11.25 ... 348.8 354.4
    time            datetime64[ns] 8B 2021-01-01T06:00:00
Data variables:
    2m_temperature  (longitude, latitude) float32 8kB 241.8 244.8 ... 260.0
    geopotential    (longitude, latitude) float32 8kB 1.453e+05 ... 1.447e+05

In [20]:
sample = source["20210105T00"]
sample

<xarray.Dataset> Size: 2MB
Dimensions:                                           (longitude: 64,
                                                       latitude: 32, level: 13)
Coordinates:
  * latitude                                          (latitude) float64 256B ...
  * level                                             (level) int64 104B 50 ....
  * longitude                                         (longitude) float64 512B ...
    time                                              datetime64[ns] 8B 2021-...
Data variables: (12/62)
    10m_u_component_of_wind                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    10m_v_component_of_wind                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    10m_wind_speed                                    (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    2m_dewpoint_temperature                           (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    2m_temperature                                    (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    above_ground                                      (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>
    ...                                                ...
    volumetric_soil_water_layer_1                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_2                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_3                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    volumetric_soil_water_layer_4                     (longitude, latitude) float32 8kB dask.array<chunksize=(64, 32), meta=np.ndarray>
    vorticity                                         (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>
    wind_speed                                        (level, longitude, latitude) float32 106kB dask.array<chunksize=(13, 64, 32), meta=np.ndarray>

In [21]:
mini_pipe = Seq([sample]) | virtual_pipeline
mini_pipe[0]

<xarray.DataArray '2m_temperature' (lon: 64, lat: 32, feats: 2)> Size: 16kB
array([[[   242.0651 , 147187.25   ],
        [   243.65332, 146933.02   ],
        [   241.94775, 146841.98   ],
        ...,
        [   267.98285, 144993.33   ],
        [   260.9061 , 144258.77   ],
        [   259.71408, 144142.75   ]],

       [[   241.76764, 147150.55   ],
        [   242.14073, 146869.69   ],
        [   238.36916, 146690.38   ],
        ...,
        [   272.44647, 145317.34   ],
        [   264.3306 , 144441.69   ],
        [   260.69818, 144215.8    ]],

       [[   241.62366, 147121.31   ],
        [   240.86768, 146812.66   ],
        [   236.65443, 146557.03   ],
        ...,
...
        ...,
        [   258.63705, 144251.39   ],
        [   255.91281, 143796.03   ],
        [   255.15414, 143934.3    ]],

       [[   243.12317, 147285.17   ],
        [   247.1    , 147134.03   ],
        [   249.23627, 147234.86   ],
        ...,
        [   259.28436, 144463.     ],
        [   257.32404, 143934.9    ],
        [   256.41342, 144001.16   ]],

       [[   242.52959, 147231.72   ],
        [   244.86807, 147017.61   ],
        [   244.73184, 147015.97   ],
        ...,
        [   262.62195, 144708.03   ],
        [   258.26828, 144088.25   ],
        [   257.99374, 144070.77   ]]], shape=(64, 32, 2), dtype=float32)
Coordinates:
  * lat       (lat) float64 256B -87.19 -81.56 -75.94 ... 75.94 81.56 87.19
  * lon       (lon) float64 512B 0.0 5.625 11.25 16.88 ... 343.1 348.8 354.4
    time      datetime64[ns] 8B 2021-01-05
  * feats     (feats) object 16B MultiIndex
  * variable  (feats) <U14 112B '2m_temperature' 'geopotential'

In [22]:
new_pipeline = pipeline | ops.ToNumpy(index_coord="time") | ops.Op(np.log, undo_func=np.exp)
new_pipeline["20210102T00"]

array([[[ 5.4922724, 11.890709 ],
        [ 5.5029845, 11.889296 ],
        [ 5.49136  , 11.888241 ],
        ...,
        [ 5.611582 , 11.891347 ],
        [ 5.577715 , 11.886796 ],
        [ 5.5528193, 11.88244  ]],

       [[ 5.4902844, 11.890874 ],
        [ 5.494515 , 11.889781 ],
        [ 5.4779296, 11.888679 ],
        ...,
        [ 5.6210537, 11.890079 ],
        [ 5.5963798, 11.887099 ],
        [ 5.556279 , 11.882638 ]],

       [[ 5.4888773, 11.891084 ],
        [ 5.4877753, 11.890449 ],
        [ 5.467345 , 11.889418 ],
        ...,
        [ 5.622796 , 11.888716 ],
        [ 5.603646 , 11.887225 ],
        [ 5.559877 , 11.882821 ]],

       ...,

       [[ 5.5018334, 11.890528 ],
        [ 5.540536 , 11.888831 ],
        [ 5.5578165, 11.888448 ],
        ...,
        [ 5.5628185, 11.890581 ],
        [ 5.5503063, 11.884717 ],
        [ 5.5493145, 11.881736 ]],

       [[ 5.4984155, 11.89053  ],
        [ 5.526256 , 11.888818 ],
        [ 5.5320835, 11.888105 ],
        .

In [23]:
(new_pipeline | new_pipeline.undo(2))["20210102T00"]

<xarray.DataArray (lon: 64, lat: 32, feats: 2)> Size: 16kB
array([[[   242.80832, 145904.7    ],
        [   245.42331, 145698.62   ],
        [   242.58694, 145545.03   ],
        ...,
        [   273.57666, 145997.81   ],
        [   264.46658, 145334.89   ],
        [   257.9638 , 144703.14   ]],

       [[   242.32611, 145928.78   ],
        [   243.35345, 145769.38   ],
        [   239.35063, 145608.77   ],
        ...,
        [   276.18024, 145812.75   ],
        [   269.44916, 145378.98   ],
        [   258.85788, 144731.84   ]],

       [[   241.98538, 145959.39   ],
        [   241.71887, 145866.72   ],
        [   236.83061, 145716.42   ],
        ...,
...
        ...,
        [   260.55618, 145886.05   ],
        [   257.31638, 145033.06   ],
        [   257.06128, 144601.33   ]],

       [[   244.30452, 145878.55   ],
        [   251.20168, 145629.03   ],
        [   252.66978, 145525.33   ],
        ...,
        [   262.68304, 146045.98   ],
        [   258.06604, 145165.9    ],
        [   257.159  , 144638.16   ]],

       [[   243.51888, 145887.6    ],
        [   247.90869, 145652.92   ],
        [   245.75847, 145515.33   ],
        ...,
        [   268.42813, 146088.77   ],
        [   259.66428, 145273.52   ],
        [   257.3424 , 144671.83   ]]], shape=(64, 32, 2), dtype=float32)
Coordinates:
  * lat       (lat) float64 256B -87.19 -81.56 -75.94 ... 75.94 81.56 87.19
  * lon       (lon) float64 512B 0.0 5.625 11.25 16.88 ... 343.1 348.8 354.4
    time      datetime64[ns] 8B 2021-01-02
  * feats     (feats) object 16B MultiIndex
  * variable  (feats) <U14 112B '2m_temperature' 'geopotential'